Repository KangHayeonn/pickplace-client, pull requests merged in 2023-07, with the labels that each got.

#81 [UPDATE]: SearchPage 검색창 수정 및 style 수정
  front/src/api/search.ts
  front/src/components/search/CategorySelector.tsx
  front/src/components/search/DistanceInput.tsx
  front/src/components/search/DistanceSlider.tsx
  front/src/components/search/SearchHeader.tsx
  front/src/components/search/SearchOptionMenu.tsx
  front/src/components/search/SearchResult.tsx
  front/src/components/search/TagSelector.tsx
  front/src/components/search/types.ts
  front/src/pages/SearchPage.tsx
  front/src/styles/base/global.scss
  front/src/styles/components/search/searchFilter.scss
  front/src/styles/components/search/searchHeader.scss
  front/src/styles/components/search/searchOptionMenu.scss
  front/src/styles/components/search/searchResult.scss
Labels: ♻ refactor, 💄 add or update UI

#84 [ADD] : 로그인 페이지 기능 구현
  front/.pnp.cjs
  front/.yarn/cache/@types-redux-actions-npm-2.6.2-cd5cdcb46e-61388ab6f5.zip
  front/.yarn/cache/@types-redux-logger-npm-3.0.9-ac1d3f05fb-c41fdc0919.zip
  front/.yarn/cache/deep-diff-npm-0.3.8-a2a66d74dd-8a0fb6cbe4.zip
  front/.yarn/cache/just-curry-it-npm-5.3.0-343c14ce2a-7a7d2e118c.zip
  front/.yarn/cache/reduce-reducers-npm-1.0.4-5b952f0836-9b3648fa50.zip
  front/.yarn/cache/redux-actions-npm-3.0.0-ba1284426b-29cbf70f76.zip
  front/.yarn/cache/redux-logger-npm-3.0.6-4c0c652262-c40f63c44c.zip
  front/package.json
  front/src/api/auth/index.ts
  front/src/api/auth/types.ts
  front/src/api/common/interceptors.ts
  front/src/api/index.ts
  front/src/components/auth/LoginForm.tsx
  front/src/pages/SamplePage.tsx
  front/src/store/index.ts
  front/src/store/lib/asyncUtils.ts
  front/src/store/modules/auth.ts
  front/src/store/modules/index.ts
  front/src/utils/tokenControl.ts
  front/yarn.lock
Labels: 🌈 update, ♻ refactor, ✨ add, ✋ code-review

#82 [ADD]: MyPage 내 리뷰 화면 구현
  front/src/assets/images/check.svg
  front/src/assets/images/clock.svg
  front/src/assets/images/edit.svg
  front/src/assets/images/pin.svg
  front/src/assets/images/profile.svg
  front/src/assets/images/star-empty.svg
  front/src/assets/images/star-for-rate.svg
  front/src/assets/images/star-full.svg
  front/src/assets/images/trash.svg
  front/src/components/common/StarRate.tsx
  front/src/components/mypage/Header.tsx
  front/src/components/mypage/reservation/DetailCard.tsx
  front/src/components/mypage/reservation/DetailContent.tsx
  front/src/components/mypage/reservation/DetailHeader.tsx
  front/src/components/mypage/reservation/ReservationDetail.tsx
  front/src/components/mypage/reservation/ResevationCard.tsx
  front/src/components/mypage/reservation/types.ts
  front/src/components/mypage/review/CreateModal.tsx
  front/src/components/mypage/review/DetailModal.tsx
  front/src/components/mypage/review/ModalForm.tsx
  front/src/components/mypage/review/MyReview.tsx
  front/src/components/mypage/review/ReviewModalHeader.tsx
  front/src/components/mypage/review/UpdateModal.tsx
  front/src/components/mypage/types.ts
  front/src/components/search/SearchHeader.tsx
  front/src/components/search/SearchResult.tsx
  front/src/components/search/detail/SearchDetailReviewInfo.tsx
  front/src/components/search/detail/SearchDetailTitle.tsx
  front/src/pages/MyPage.tsx
  front/src/styles/components/common/modalForm.scss
  front/src/styles/components/common/starRate.scss
  front/src/styles/components/mypage/mypage.scss
  front/src/styles/components/mypage/review/detailModal.scss
  front/src/styles/components/mypage/review/modalForm.scss
  front/src/styles/components/mypage/review/myReview.scss
  front/src/styles/components/mypage/review/reviewModalHeader.scss
  front/src/styles/components/mypage/review/updateModal.scss
  front/src/utils/mock/myReviewList.ts
Labels: ✨ add, 💄 add or update UI, ✋ code-review

#98 [ADD] : 토큰 재발급 기능 구현
  front/src/api/common/interceptors.ts
Labels: ✨ add, ✋ code-review

#99 [ADD] : 공통 예외처리 핸들링 구현 - 토스트메시지 사용
  front/src/App.tsx
  front/src/api/common/interceptors.ts
  front/src/components/auth/LoginForm.tsx
  front/src/components/auth/SignupForm.tsx
  front/src/components/common/ToastBox.tsx
  front/src/pages/SamplePage.tsx
  front/src/store/modules/common.ts
  front/src/store/modules/index.ts
  front/src/store/modules/sample.ts
Labels: 🌈 update, ✨ add, ✋ code-review

#100 [ADD]: 검색 결과 무한스크롤 및 지도 연동
  front/src/assets/images/place-guestHouse-img.svg
  front/src/assets/images/place-hotel-img.svg
  front/src/assets/images/place-partyRoom-img.svg
  front/src/assets/images/place-pension-img.svg
  front/src/components/common/GetCategoryImage.ts
  front/src/components/map/Map.tsx
  front/src/components/map/MarkerHtml.tsx
  front/src/components/search/SearchResult.tsx
  front/src/components/search/types.ts
  front/src/components/search/useIntersectionObserver.ts
  front/src/components/search/useViewportObserver.tsx
  front/src/pages/SearchPage.tsx
  front/src/styles/base/variable.scss
  front/src/styles/components/map/mapModal.scss
  front/src/styles/components/search/searchResult.scss
  front/src/utils/mock/markerList.ts
Labels: ✨ add, 💄 add or update UI, ✋ code-review

#102 [ADD] : 카카오 소셜 로그인 기능 구현
  front/src/api/auth/index.ts
  front/src/api/common/interceptors.ts
  front/src/components/auth/LoginForm.tsx
  front/src/components/common/Loading.tsx
  front/src/pages/RedirectPage.tsx
  front/src/router/Router.tsx
  front/src/store/modules/auth.ts
  front/src/styles/components/common/loading.scss
Labels: 🌈 update, ✨ add, 💄 add or update UI, ✋ code-review

#91 [ADD]: admin api 연동
  front/src/api/admin/index.ts
  front/src/api/admin/types.ts
  front/src/api/common/interceptors.ts
  front/src/api/mypage/index.ts
  front/src/api/mypage/types.ts
  front/src/api/review/index.ts
  front/src/components/admin/ManagePlace/CreatePlace/AddressForm.tsx
  front/src/components/admin/ManagePlace/CreatePlace/CreatePlace.tsx
  front/src/components/admin/ManagePlace/CreatePlace/PlaceForm.tsx
  front/src/components/admin/ManagePlace/ManagePlaceDetail.tsx
  front/src/components/admin/ManagePlace/PlaceCard.tsx
  front/src/components/admin/ManagePlace/PlaceHeader.tsx
  front/src/components/admin/ManagePlace/PlaceManageFunc.ts
  front/src/components/admin/ManagePlace/RoomCard.tsx
  front/src/components/admin/ManagePlace/UpdatePlace.tsx
  front/src/components/admin/ManageReservation/ManageReservation.tsx
  front/src/components/admin/ManageReservation/ManageReservationDetail.tsx
  front/src/components/admin/types.ts
  front/src/components/mypage/Header.tsx
  front/src/components/mypage/reservation/DetailContent.tsx
  front/src/components/mypage/reservation/DetailHeader.tsx
  front/src/components/mypage/reservation/Reservation.tsx
  front/src/components/mypage/reservation/ReservationDetail.tsx
  front/src/components/mypage/reservation/ResevationCard.tsx
  front/src/components/mypage/reservation/types.ts
  front/src/components/mypage/review/CreateModal.tsx
  front/src/components/mypage/review/DetailModal.tsx
  front/src/components/mypage/review/MyReview.tsx
  front/src/components/mypage/review/ReviewCard.tsx
  front/src/components/mypage/review/ReviewModalHeader.tsx
  front/src/components/mypage/review/UpdateModal.tsx
  front/src/components/mypage/types.ts
  front/src/components/mypage/userInfo/UpdateUserInfo.tsx
  front/src/components/mypage/userInfo/UserInfo.tsx
  front/src/styles/components/admin/managePlace/createPlace/addressForm.scss
  front/src/styles/components/admin/managePlace/managePlace.scss
  front/src/styles/components/admin/managePlace/managePlaceDetail.scss
  front/src/styles/components/admin/managePlace/placeHeader.scss
  front/src/styles/components/admin/managePlace/roomCard.scss
  front/src/styles/components/mypage/reservation/detailHeader.scss
  front/src/styles/components/mypage/review/reviewModal.scss
Labels: ✨ add, 💄 add or update UI, ✋ code-review
