Repository KangHayeonn/pickplace-client, pull requests merged in 2023-08, with the labels that each got.

#104 [ADD]: MyPage 수정사항 반영
  front/src/api/admin/index.ts
  front/src/api/mypage/index.ts
  front/src/api/review/index.ts
  front/src/components/admin/ManagePlace/CreatePlace/CreatePlace.tsx
  front/src/components/admin/ManagePlace/ManagePlaceDetail.tsx
  front/src/components/admin/ManagePlace/UpdatePlace.tsx
  front/src/components/admin/ManageReservation/ManageReservationDetail.tsx
  front/src/components/common/GetCategoryImage.ts
  front/src/components/mypage/ConfirmModal.tsx
  front/src/components/mypage/DeleteConfirmModal.tsx
  front/src/components/mypage/reservation/DetailContent.tsx
  front/src/components/mypage/reservation/DetailHeader.tsx
  front/src/components/mypage/reservation/ReservationDetail.tsx
  front/src/components/mypage/reservation/ResevationCard.tsx
  front/src/components/mypage/reservation/types.ts
  front/src/components/mypage/review/CreateModal.tsx
  front/src/components/mypage/review/DetailModal.tsx
  front/src/components/mypage/review/ModalForm.tsx
  front/src/components/mypage/review/MyReview.tsx
  front/src/components/mypage/review/ReviewCard.tsx
  front/src/components/mypage/review/ReviewModalHeader.tsx
  front/src/components/mypage/review/UpdateModal.tsx
  front/src/components/mypage/types.ts
  front/src/styles/components/common/modalForm.scss
Labels: 🌈 update, 💄 add or update UI, ✋ code-review

#108 [ADD] : 공간 상세 페이지 기능 구현
  front/src/api/common/interceptors.ts
  front/src/api/review/index.ts
  front/src/api/search/index.ts
  front/src/api/search/types.ts
  front/src/components/common/Calendar.tsx
  front/src/components/common/SelectBox.tsx
  front/src/components/search/SearchResult.tsx
  front/src/components/search/detail/SearchDetailInfo.tsx
  front/src/components/search/detail/SearchDetailList.tsx
  front/src/components/search/detail/SearchDetailReservation.tsx
  front/src/components/search/detail/SearchDetailRoomInfo.tsx
  front/src/components/search/detail/SearchDetailTitle.tsx
  front/src/pages/SamplePage.tsx
  front/src/pages/SearchDetailPage.tsx
  front/src/store/modules/index.ts
  front/src/store/modules/searchDetail.ts
  front/src/styles/components/common/selectBox.scss
  front/src/styles/components/search/detail/searchDetailList.scss
  front/src/styles/components/search/detail/searchDetailReservation.scss
  front/src/utils/dataFormat.ts
Labels: 🌈 update, ✨ add, 💄 add or update UI, ✋ code-review

#114 [ADD]: toast message 추가
  front/src/api/admin/index.ts
  front/src/components/admin/ManagePlace/CreatePlace/CreatePlace.tsx
  front/src/components/admin/ManagePlace/PlaceManageFunc.ts
  front/src/components/admin/ManageReservation/ManageReservationDetail.tsx
  front/src/components/admin/ManageReservation/ReservedCard.tsx
  front/src/components/admin/ReservationBtns.tsx
  front/src/components/admin/types.ts
  front/src/components/mypage/review/CreateModal.tsx
  front/src/components/mypage/review/UpdateModal.tsx
  front/src/styles/components/admin/reservationBtn.scss
Labels: ✨ add, ✋ code-review

#111 [UPDATE]: MainPage 지도 default list 설정
  front/src/components/admin/ManagePlace/CreatePlace/CategorySelector.tsx
  front/src/components/common/GetCategoryImage.ts
  front/src/components/common/SearchForm.tsx
  front/src/components/map/MarkerHtml.tsx
  front/src/components/search/SearchHeader.tsx
  front/src/components/search/SearchOptionMenu.tsx
  front/src/components/search/SearchResult.tsx
  front/src/components/search/types.ts
  front/src/pages/MainPage.tsx
  front/src/pages/SearchPage.tsx
  front/src/store/modules/auth.ts
  front/src/store/modules/index.ts
  front/src/store/modules/optionForm.ts
  front/src/store/modules/search.ts
  front/src/store/modules/searchForm.ts
  front/src/store/modules/searchResult.ts
  front/src/utils/mock/markerList.ts
  front/src/utils/mock/searchList.ts
Labels: ✨ add, ✋ code-review

#109 [UPDATE]: SearchPage 리팩토링
  front/src/components/common/SearchForm.tsx
  front/src/components/search/SearchFilter.tsx
  front/src/components/search/SearchHeader.tsx
  front/src/components/search/SearchOptionMenu.tsx
  front/src/components/search/SearchResult.tsx
  front/src/pages/MainPage.tsx
  front/src/pages/SearchPage.tsx
  front/src/store/modules/search.ts
  front/src/styles/components/search/searchFilter.scss
  front/src/styles/components/search/searchHeader.scss
  front/src/styles/components/search/searchResult.scss
Labels: ♻ refactor, ✋ code-review

#118 [UPDATE]: style 수정 및 navigate state 삭제
  front/src/components/admin/ManagePlace/ManagePlaceDetail.tsx
  front/src/components/admin/ManagePlace/PlaceCard.tsx
  front/src/components/admin/ManageReservation/ManageReservation.tsx
  front/src/components/admin/ManageReservation/ManageReservationDetail.tsx
  front/src/components/admin/ManageReservation/ReservedCard.tsx
  front/src/components/admin/types.ts
  front/src/components/mypage/reservation/ReservationDetail.tsx
  front/src/components/mypage/reservation/ResevationCard.tsx
  front/src/styles/components/admin/managePlace/managePlaceDetail.scss
  front/src/styles/components/admin/managePlace/placeHeader.scss
  front/src/styles/components/admin/manageReservation/manageReservation.scss
  front/src/styles/components/admin/manageReservation/manageReservationDetail.scss
Labels: 🌈 update, 💄 add or update UI

#119 [UPDATE]: searchPage issue 해결
  front/src/components/search/SearchHeader.tsx
  front/src/components/search/SearchResult.tsx
  front/src/pages/SearchPage.tsx
  front/src/store/modules/optionForm.ts
  front/src/styles/components/search/search.scss
  front/src/styles/components/search/searchHeader.scss
  front/src/styles/components/search/searchResult.scss
Labels: 🌈 update, 💄 add or update UI, ✋ code-review

#122 [UPDATE]: AdminPage 수정사항반영
  front/src/components/admin/ManagePlace/ManagePlaceDetail.tsx
  front/src/components/admin/ManageReservation/ManageReservationDetail.tsx
  front/src/components/admin/ManageReservation/ReservedCard.tsx
  front/src/components/mypage/reservation/ReservationDetail.tsx
  front/src/styles/components/admin/managePlace/managePlaceDetail.scss
  front/src/styles/components/admin/manageReservation/manageReservation.scss
  front/src/styles/components/mypage/reservation/reservationCard.scss
Labels: 🌈 update, 💄 add or update UI, ✋ code-review

#112 [ADD] : 예약 & 결제 마크업 및 기능 구현
  front/src/api/reservation/index.ts
  front/src/api/reservation/types.ts
  front/src/assets/images/kbstar-bank.svg
  front/src/assets/images/kebhana-bank.svg
  front/src/assets/images/place-partyRoom-img.png
  front/src/assets/images/place-partyRoom-img.svg
  front/src/assets/images/shinhan-bank.svg
  front/src/assets/images/woori-bank.svg
  front/src/components/common/CheckBox.tsx
  front/src/components/common/GetCategoryImage.ts
  front/src/components/common/modal/Modals.tsx
  front/src/components/reservation/AgreementForm.tsx
  front/src/components/reservation/PaymentForm.tsx
  front/src/components/reservation/PaymentInfo.tsx
  front/src/components/reservation/ReservationForm.tsx
  front/src/components/reservation/ReservationInfo.tsx
  front/src/components/reservation/ReservationTemplate.tsx
  front/src/components/reservation/modal/AccountModal.tsx
  front/src/components/reservation/modal/CardValidationModal.tsx
  front/src/components/reservation/modal/PaymentModal.tsx
  front/src/components/reservation/modal/QRCodeModal.tsx
  front/src/components/reservation/modal/ReservationInfoModal.tsx
  front/src/components/reservation/modal/ReservationResultModal.tsx
  front/src/components/search/detail/SearchDetailInfo.tsx
  front/src/components/search/detail/SearchDetailList.tsx
  front/src/components/search/detail/SearchDetailReservation.tsx
  front/src/components/search/detail/SearchDetailReviewInfo.tsx
  front/src/components/search/detail/SearchDetailRoomInfo.tsx
  front/src/components/search/detail/SearchDetailTitle.tsx
  front/src/components/search/detail/SearchReviewDetailModal.tsx
  front/src/pages/QRPasswordPage.tsx
  front/src/pages/SamplePage.tsx
  front/src/pages/SearchDetailPage.tsx
  front/src/router/Router.tsx
  front/src/store/modules/index.ts
  front/src/store/modules/reservation.ts
  front/src/store/modules/searchDetail.ts
  front/src/styles/components/reservation/modal/accountModal.scss
  front/src/styles/components/reservation/modal/cardValidationModal.scss
  front/src/styles/components/reservation/modal/paymentModal.scss
  front/src/styles/components/reservation/modal/qrCodeModal.scss
  front/src/styles/components/reservation/modal/reservationInfoModal.scss
  front/src/styles/components/reservation/modal/reservationResultModal.scss
  front/src/styles/components/reservation/paymentForm.scss
  front/src/styles/components/reservation/qrPassword.scss
  front/src/styles/components/search/detail/searchDetailReviewInfo.scss
  front/src/styles/components/search/searchHeader.scss
  front/src/utils/dataFormat.ts
Labels: 🌈 update, ✨ add, 💄 add or update UI, ✋ code-review

#126 [UPDATE] : QR 결제 기능 추가 & api 예외처리 및 추가 이슈 수정
  front/src/api/common/commonInterceptors.ts
  front/src/api/index.ts
  front/src/api/reservation/index.ts
  front/src/api/review/index.ts
  front/src/components/admin/ManagePlace/UpdatePlace.tsx
  front/src/components/common/Calendar.tsx
  front/src/components/common/DropDown.tsx
  front/src/components/common/modal/UseModals.tsx
  front/src/components/mypage/review/MyReview.tsx
  front/src/components/reservation/ReservationInfo.tsx
  front/src/components/reservation/ReservationTemplate.tsx
  front/src/components/reservation/modal/CardValidationModal.tsx
  front/src/components/reservation/modal/PaymentModal.tsx
  front/src/components/reservation/modal/QRCodeModal.tsx
  front/src/components/reservation/modal/ReservationInfoModal.tsx
  front/src/components/reservation/modal/ReservationResultModal.tsx
  front/src/components/search/SearchResult.tsx
  front/src/components/search/detail/SearchDetailReviewInfo.tsx
  front/src/components/search/detail/SearchDetailRoomInfo.tsx
  front/src/components/search/detail/SearchDetailTitle.tsx
  front/src/components/search/detail/SearchReviewDetailModal.tsx
  front/src/pages/LoginPage.tsx
  front/src/pages/QRPasswordPage.tsx
  front/src/pages/SamplePage.tsx
  front/src/pages/SearchDetailPage.tsx
  front/src/store/index.ts
  front/src/store/modules/reservation.ts
  front/src/styles/components/mypage/review/reviewModalHeader.scss
Labels: 🌈 update, 🐛 bug, ✨ add, 💄 add or update UI, ✋ code-review

#127 [ADD] : 회원 가입 이메일 인증 기능 추가 & 회원 탈퇴 기능 구현 & router guard 설정
  front/src/api/auth/index.ts
  front/src/components/auth/SignupForm.tsx
  front/src/components/mypage/userInfo/UserInfo.tsx
  front/src/components/reservation/modal/CardValidationModal.tsx
  front/src/components/search/detail/SearchDetailRoomInfo.tsx
  front/src/router/PrivateRoute.tsx
  front/src/router/Router.tsx
Labels: 🌈 update, ✨ add, 💄 add or update UI, ✋ code-review

#128 [ADD] : 기능 테스트 후 이슈 수정 & QR 결제 기능 & 회원 탈퇴 기능 & 회원가입 메일링 연동 구현
  front/src/api/auth/index.ts
  front/src/api/common/commonInterceptors.ts
  front/src/api/index.ts
  front/src/api/reservation/index.ts
  front/src/api/review/index.ts
  front/src/components/admin/ManagePlace/UpdatePlace.tsx
  front/src/components/auth/SignupForm.tsx
  front/src/components/common/Calendar.tsx
  front/src/components/common/DropDown.tsx
  front/src/components/common/modal/UseModals.tsx
  front/src/components/mypage/review/MyReview.tsx
  front/src/components/mypage/userInfo/UserInfo.tsx
  front/src/components/reservation/ReservationInfo.tsx
  front/src/components/reservation/ReservationTemplate.tsx
  front/src/components/reservation/modal/CardValidationModal.tsx
  front/src/components/reservation/modal/PaymentModal.tsx
  front/src/components/reservation/modal/QRCodeModal.tsx
  front/src/components/reservation/modal/ReservationInfoModal.tsx
  front/src/components/reservation/modal/ReservationResultModal.tsx
  front/src/components/search/SearchResult.tsx
  front/src/components/search/detail/SearchDetailReviewInfo.tsx
  front/src/components/search/detail/SearchDetailRoomInfo.tsx
  front/src/components/search/detail/SearchDetailTitle.tsx
  front/src/components/search/detail/SearchReviewDetailModal.tsx
  front/src/pages/LoginPage.tsx
  front/src/pages/QRPasswordPage.tsx
  front/src/pages/SamplePage.tsx
  front/src/pages/SearchDetailPage.tsx
  front/src/router/PrivateRoute.tsx
  front/src/router/Router.tsx
  front/src/store/index.ts
  front/src/store/modules/reservation.ts
  front/src/styles/components/mypage/review/reviewModalHeader.scss
Labels: 🌈 update, ♻ refactor, 🐛 bug, ✨ add, 💄 add or update UI

#129 [BUGFIX] : QR 결제 페이지 useEffect 두번 호출 이슈 해결
  front/src/api/auth/index.ts
  front/src/components/auth/PasswordForm.tsx
  front/src/components/mypage/userInfo/UserInfo.tsx
  front/src/components/reservation/modal/ReservationInfoModal.tsx
  front/src/pages/RedirectPage.tsx
  front/src/styles/components/auth/passwordForm.scss
Labels: 🌈 update, 🐛 bug, ✨ add, 💄 add or update UI, ✋ code-review

#130 [ADD] : 비밀번호 변경/찾기 기능 구현 & QR 결제 페이지 이슈 해결 및 카카오 소셜 로그인 예외처리 추가
  front/src/api/auth/index.ts
  front/src/components/auth/PasswordForm.tsx
  front/src/components/mypage/userInfo/UserInfo.tsx
  front/src/components/reservation/modal/ReservationInfoModal.tsx
  front/src/pages/RedirectPage.tsx
  front/src/styles/components/auth/passwordForm.scss
Labels: 🌈 update, 🐛 bug, ✨ add, 💄 add or update UI
